name: Run the integration tests

on:
  push:
    branches:
      - main

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_USER: user1
      DB_PASSWORD: mealpass
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # Install dependencies
      - run: npm install -g mocha
      

      # Run tests
      - run: npm test
